title: <p align="center"> Sajan Kedia </p>
logo: /assets/img/839_695656782722177_1716881690510392068_n.jpg
theme: jekyll-theme-minimal
title: My Robotics Projects
description: A showcase of my robotics projects.

collections:
  projects:
    output: true
